### ISSUE TITLE
What will happen if draft contains stretches of Ns?

### ISSUE THREAD

**Issue by ms-gx** [lbcb-sci/racon#39]
What will happen if I polish a draft genome which contains stretches of Ns? As for example generated by Flye when scaffolding contigs. It is adding 100 Ns in between if I remember correctly.

I would add parameter "-u" but I assume this has influence on my question.

**Comment by rvaser** [comment]
Hello,
if the stretch of Ns is either at the beginning or end of a 500bp window, it might get truncated. My best bet would be to polish your assembly before scaffolding.

Option `-u` is used when you want all of your contigs in the output file, otherwise those that are not polished at all will be dropped.

Best regards,
Robert

**Comment by ms-gx** [comment]
Thank you for the quick response! Yes, in the meantime I saw that racon truncates those stretches of Ns. There is no way to avoid this I guess?

**Comment by rvaser** [comment]
Actually, there is the `--no-trimming` option which does that. Forgot about it :D

**Comment by ms-gx** [comment]
OK, that sounds promising! So with "--no-trimming" racon will basically just correct regions where it is able to map reads and the others it will leave untouched? I did not really understand this parameter from the help...

**Comment by rvaser** [comment]
Yes, everything that can be corrected with the reads will be, and nothing shall be trimmed away due to low coverage.

**Comment by ms-gx** [comment]
OK, many thanks!
