### ISSUE TITLE
recommendations for read correction

### ISSUE THREAD

**Issue by dcopetti** [lbcb-sci/racon#40]
Hi,
I am considering whether to use Racon for error correct raw ONT reads (>20 kb, QV>=8, about 70 Gb or 15x coverage of my repeat-rich genome) and I wonder if you have any settings to recommend, both in the minimap2 and in the Racon steps. I replaced the headers with a short string of unique numbers (up to 9 characters).
Examples:
`minimap2 -t 90 -x ava-ont -o alignment.paf reads.fa reads.fa`
should I then use any of the `-c -I -N` parameters? 
`racon -f -t 90 reads.fa alignment.paf reads.fa`
should I also consider `-q` and `-e` for example?
my concerns are the space required for the error correction (I have 15-17 TB on that machine), memory (1 TB max), and parallelization (I have 96 CPUs but does Racon scale linearly up to there or should I run jobs in parallel?)
Thanks!

**Comment by rvaser** [comment]
Hi Dario,
the commands look fine as is. You might want to consider declaring a value for `-N` so the resulting .paf file does not explode, but that might affect accuracy. The memory consumption is bound by the .paf and .fa files, hopefully it will fit into the 1TB you have. If I recall correctly, I got a 2TB .paf file when overlapping reads with each other for a plant genome of similar size (the coverage was a bit bigger), but I was not correcting the reads and could not even if I wanted to, due to the size of the .paf file. Regarding parallelization, Racon should scale well and I think you do not need to run several jobs in parallel.

Best regards,
Robert

**Comment by splaisan** [comment]
> Hi,
> I am considering whether to use Racon for error correct raw ONT reads (>20 kb, QV>=8, about 70 Gb or 15x coverage of my repeat-rich genome) and I wonder if you have any settings to recommend, both in the minimap2 and in the Racon steps. I replaced the headers with a short string of unique numbers (up to 9 characters).
> Examples:
> `minimap2 -t 90 -x ava-ont -o alignment.paf reads.fa reads.fa`
> should I then use any of the `-c -I -N` parameters?
> `racon -f -t 90 reads.fa alignment.paf reads.fa`
> should I also consider `-q` and `-e` for example?
> my concerns are the space required for the error correction (I have 15-17 TB on that machine), memory (1 TB max), and parallelization (I have 96 CPUs but does Racon scale linearly up to there or should I run jobs in parallel?)
> Thanks!

Hi @dcopetti,
I am curious to hear how well the correction worked, what happens when you plot read len gth vs read meanqual after doing so for instance. Could you please post such a plot before and after racon polishing.

@rvaser when doing read correction, is there a bonus in performing more than one round of polishing and if yeas would you polish the first round with raw reads or itself? (thanks)

**Comment by rvaser** [comment]
Hi Stephane,
I do not recall that we ever run two iterations of self error correction nor do I know if it is worth. I would opt for raw reads in the second round.

Best regards,
Robert

**Comment by splaisan** [comment]
Thanks a lot for the info Robert

**Comment by dcopetti** [comment]
Hi @rvaser ,
I tried aligning all vs all reads above 10 kb and just with that I get a paf file of 19 TB: too much it didn't even complete.
So I am thinking to error correct e.g. only reads above 20 kb (18x coverage) with reads above 10 kb (31x) in order to have many alignments to only the longer backbones. Does it make sense? Should I use only >20 kb reads for both query and target?
I have very minimal headers, and I can also drop a few minimap alignments (`-N` 4 or 3)
The minimap command would be (target and query in this order)
`minimap2 -t 90 -x ava-ont -o alignment.paf 20kb_reads.fa 10kb_reads.fa`
and the racon command:
`racon -f -t 90 10kb_reads.fa alignment.paf 20kb_reads.fa`
what do you think?

**Comment by splaisan** [comment]
Dear @dcopetti ,
I did a run recently and the advices of @rvaser  somewhere on these pages were very useful.
I took my input in bins of only few 1000's reads and corrected them against the full data, the intermediate file did not grow too large and I deleted it before taking the next bin so that my storage did not fill up significantly with the alignments (I used sam but paf should be no different).
It took a huge time with about 3 days on 88 cores for only 250MB of read input but it ran and finished OK.
You can access my method in details on [my wiki page](https://github.com/splaisan/analyses/wiki/racon_pacbio_polishing).
I would have loved to use our Gridion GPU to speed up racon but the necessary software is not installed by ONT and they do not support installing the NVIDIA developer tools. Sad as this would probably have sped it all up quite some.
Good luck

**Comment by dcopetti** [comment]
hi @splaisan,
that's right, the target files could be of any size!I will give it a try, thanks a lot for the hint.
And very nice documentation, thanks for sharing!

Dario

**Comment by dcopetti** [comment]
Hi,
I tried running racon on a subset of the input files and the job got killed:
```
(py3) bash-4.2$ ls -lrth
total 2.7T
-rwx------. 1 copettid mpb 665M Jul  8 17:23 Rabiosa_G303_all_up150kb_q7_h.fa.gz
-rw-r--r--. 1 copettid mpb 2.6T Jul  9 07:30 Rab_up150kb_ava.paf
-rw-r--r--. 1 copettid mpb 147G Jul  9 08:12 Rabiosa_G303_all_min10kb_q7_h.fa
(py3) bash-4.2$racon -f -t 35 Rabiosa_G303_all_min10kb_q7_h.fa Rab_up150kb_ava.paf Rabiosa_G303_all_up150kb_q7_h.fa.gz >Rabiosa_G303_all_up150kb_raconEC.fa
[racon::Polisher::initialize] loaded target sequences 21.852293 s
[racon::Polisher::initialize] loaded sequences 787.053573 s
Killed
```
I can't figure out why, I wonder if racon is maybe loading on memory the whole paf file. If so, I will go for @splaisan's script
thanks

**Comment by splaisan** [comment]
if you use my script, make sure that you do not ask more cpu than what you have and check in htop the current memory usage during the job and maybe just before crash!
I have here 512GB RAM which is very comfortable
Also, try first with 100 reads to see that the code in its whole works

**Comment by splaisan** [comment]
your PAF is far too big I think to do this in one GO

**Comment by dcopetti** [comment]
Update: I am giving up on using Racon for error correcting reads: an input of 2.5 Gb created a 11 TB sam file in 12 days - and was still not completed. not the right tool for my data. @splaisan : your script worked well though, thanks for sharing!
